/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    clinicians: Clinician;
    staff: Staff;
    services: Service;
    'couples-formats': CouplesFormat;
    offices: Office;
    articles: Article;
    'resource-link-groups': ResourceLinkGroup;
    faqs: Faq;
    helplines: Helpline;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clinicians: CliniciansSelect<false> | CliniciansSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'couples-formats': CouplesFormatsSelect<false> | CouplesFormatsSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'resource-link-groups': ResourceLinkGroupsSelect<false> | ResourceLinkGroupsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    helplines: HelplinesSelect<false> | HelplinesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-hero': HomeHero;
    'first-visit': FirstVisit;
    rates: Rate;
    coaching: Coaching;
    'contact-settings': ContactSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-hero': HomeHeroSelect<false> | HomeHeroSelect<true>;
    'first-visit': FirstVisitSelect<false> | FirstVisitSelect<true>;
    rates: RatesSelect<false> | RatesSelect<true>;
    coaching: CoachingSelect<false> | CoachingSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors can manage content but not other users.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  /**
   * Optional photo credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinicians".
 */
export interface Clinician {
  id: number;
  /**
   * URL-safe id, e.g. "dr-diann-sanford". No spaces.
   */
  slug: string;
  name: string;
  credentials?: string | null;
  role?: string | null;
  image?: (number | null) | Media;
  quote?: string | null;
  specialties?: string[] | null;
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  education?: string[] | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: number;
  /**
   * URL-safe id, e.g. "dr-diann-sanford". No spaces.
   */
  slug: string;
  name: string;
  role?: string | null;
  email?: string | null;
  image?: (number | null) | Media;
  bio?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Must match an icon available in the site theme.
   */
  icon?:
    ('heart' | 'users' | 'clipboard' | 'home' | 'sun' | 'sparkles' | 'brain' | 'shield' | 'activity' | 'wind') | null;
  body: string;
  /**
   * Optional link, e.g. /couples.
   */
  href?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couples-formats".
 */
export interface CouplesFormat {
  id: number;
  /**
   * URL-safe id, e.g. "dr-diann-sanford". No spaces.
   */
  slug: string;
  title: string;
  tagline?: string | null;
  image?: (number | null) | Media;
  price?: string | null;
  duration?: string | null;
  summary?: string | null;
  quote?: string | null;
  details?: string[] | null;
  /**
   * Optional structured agenda (intensives & retreats).
   */
  agenda?: {
    intro?: string | null;
    inAdvance?: string[] | null;
    partsIntro?: string | null;
    parts?:
      | {
          title: string;
          note?: string | null;
          points?: string[] | null;
          id?: string | null;
        }[]
      | null;
    lunchNote?: string | null;
    closing?: string | null;
  };
  guarantee?: string | null;
  /**
   * Register / Pay URL.
   */
  register?: string | null;
  registerNote?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  label: string;
  lines?: string[] | null;
  image?: (number | null) | Media;
  /**
   * Google Maps URL.
   */
  maps?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * URL-safe id, e.g. "dr-diann-sanford". No spaces.
   */
  slug: string;
  title: string;
  category?: string | null;
  /**
   * Must match an icon available in the site theme.
   */
  icon?:
    ('heart' | 'users' | 'clipboard' | 'home' | 'sun' | 'sparkles' | 'brain' | 'shield' | 'activity' | 'wind') | null;
  excerpt?: string | null;
  body?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional pull-quote.
   */
  quote?: string | null;
  /**
   * Optional embedded YouTube video.
   */
  video?: {
    title?: string | null;
    /**
     * YouTube video ID (not the full URL).
     */
    youtube?: string | null;
  };
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-link-groups".
 */
export interface ResourceLinkGroup {
  id: number;
  heading: string;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  q: string;
  a: string;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helplines".
 */
export interface Helpline {
  id: number;
  name: string;
  detail?: string | null;
  href?: string | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clinicians';
        value: number | Clinician;
      } | null)
    | ({
        relationTo: 'staff';
        value: number | Staff;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'couples-formats';
        value: number | CouplesFormat;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'resource-link-groups';
        value: number | ResourceLinkGroup;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'helplines';
        value: number | Helpline;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinicians_select".
 */
export interface CliniciansSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  credentials?: T;
  role?: T;
  image?: T;
  quote?: T;
  specialties?: T;
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  education?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  email?: T;
  image?: T;
  bio?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  body?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couples-formats_select".
 */
export interface CouplesFormatsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  tagline?: T;
  image?: T;
  price?: T;
  duration?: T;
  summary?: T;
  quote?: T;
  details?: T;
  agenda?:
    | T
    | {
        intro?: T;
        inAdvance?: T;
        partsIntro?: T;
        parts?:
          | T
          | {
              title?: T;
              note?: T;
              points?: T;
              id?: T;
            };
        lunchNote?: T;
        closing?: T;
      };
  guarantee?: T;
  register?: T;
  registerNote?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  label?: T;
  lines?: T;
  image?: T;
  maps?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  category?: T;
  icon?: T;
  excerpt?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  quote?: T;
  video?:
    | T
    | {
        title?: T;
        youtube?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  references?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource-link-groups_select".
 */
export interface ResourceLinkGroupsSelect<T extends boolean = true> {
  heading?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  q?: T;
  a?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helplines_select".
 */
export interface HelplinesSelect<T extends boolean = true> {
  name?: T;
  detail?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName?: string | null;
  tagline?: string | null;
  intro?: string | null;
  phone?: string | null;
  /**
   * e.g. tel:9724272050
   */
  phoneHref?: string | null;
  email?: string | null;
  fax?: string | null;
  /**
   * Client portal URL.
   */
  portal?: string | null;
  /**
   * Payment / register URL.
   */
  payment?: string | null;
  social?: {
    linkedin?: string | null;
    facebook?: string | null;
    psychologyToday?: string | null;
  };
  insurance?: string[] | null;
  /**
   * Brand imagery used across the site.
   */
  images?: {
    founderPortrait?: (number | null) | Media;
    leaves?: (number | null) | Media;
    confidentiality?: (number | null) | Media;
    gallery?:
      | {
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero".
 */
export interface HomeHero {
  id: number;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  founderQuote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "first-visit".
 */
export interface FirstVisit {
  id: number;
  goals?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  expect?: string[] | null;
  confidentiality?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates".
 */
export interface Rate {
  id: number;
  intro?: string | null;
  note?: string | null;
  items?:
    | {
        label: string;
        price: string;
        id?: string | null;
      }[]
    | null;
  cancellation?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching".
 */
export interface Coaching {
  id: number;
  intro?: string | null;
  coaches?:
    | {
        name: string;
        role?: string | null;
        image?: (number | null) | Media;
        price?: string | null;
        priceHref?: string | null;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    heading?: string | null;
    intro?: string | null;
    rows?:
      | {
          type: string;
          standard?: string | null;
          intro?: string | null;
          pkg?: string | null;
          pkgRate?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  /**
   * Where contact-form submissions are delivered. Can also be set via CONTACT_FORM_TO_EMAIL env.
   */
  toEmail?: string | null;
  successMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  intro?: T;
  phone?: T;
  phoneHref?: T;
  email?: T;
  fax?: T;
  portal?: T;
  payment?: T;
  social?:
    | T
    | {
        linkedin?: T;
        facebook?: T;
        psychologyToday?: T;
      };
  insurance?: T;
  images?:
    | T
    | {
        founderPortrait?: T;
        leaves?: T;
        confidentiality?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-hero_select".
 */
export interface HomeHeroSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  founderQuote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "first-visit_select".
 */
export interface FirstVisitSelect<T extends boolean = true> {
  goals?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  expect?: T;
  confidentiality?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rates_select".
 */
export interface RatesSelect<T extends boolean = true> {
  intro?: T;
  note?: T;
  items?:
    | T
    | {
        label?: T;
        price?: T;
        id?: T;
      };
  cancellation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching_select".
 */
export interface CoachingSelect<T extends boolean = true> {
  intro?: T;
  coaches?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        price?: T;
        priceHref?: T;
        bio?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        heading?: T;
        intro?: T;
        rows?:
          | T
          | {
              type?: T;
              standard?: T;
              intro?: T;
              pkg?: T;
              pkgRate?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  toEmail?: T;
  successMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}